# Generated by Django 5.0.6 on 2024-07-03 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_classroom_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='Address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.address'),
        ),
    ]
