# Generated by Django 5.0.6 on 2024-07-03 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_address_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='classRoom',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
