# Generated by Django 5.0.6 on 2024-07-03 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0005_remove_classroom_address_remove_classroom_topic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=120)),
                ('c_code', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=300)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('c_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.courses')),
                ('dept_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.dept')),
            ],
        ),
    ]
