# Generated by Django 5.0.6 on 2024-07-03 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='biodata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300)),
                ('email_contact', models.CharField(max_length=300)),
                ('phon_contact', models.CharField(max_length=300)),
                ('s_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.students')),
            ],
        ),
    ]
